services:
  - type: web
    name: beu-syllabus-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: 5861904079
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true
